source:
  docker_image: "airbyte/source-github:latest"
  config:
    credentials:
      option_title: "PAT Credentials"
      personal_access_token: "<PAT-TOKEN>"
    repositories:
      - vaibhav-aiplanet/code-evaluation-agent
    api_url: "https://api.github.com/"
  streams: commits
